# Generated by Django 6.0.4 on 2026-04-28 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Chưa thanh toán'), ('PAID', 'Đã thanh toán'), ('REFUNDED', 'Đã hoàn tiền')], default='UNPAID', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinical.medicalresult')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.patient')),
            ],
        ),
    ]
