# Generated by Django 6.0.4 on 2026-04-28 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('Vien', 'Viên'), ('Goi', 'Gói'), ('Chai', 'Chai'), ('Ong', 'Ống'), ('Tuyp', 'Tuýp'), ('Vi', 'Vỉ')], max_length=10)),
                ('effect', models.TextField()),
                ('current_selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('import_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_imported', models.PositiveIntegerField()),
                ('quantity_remaining', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('import_date', models.DateField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_advice', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinical.medicalresult')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('dosage', models.CharField(max_length=255)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pharmacy.prescription')),
            ],
        ),
    ]
